[[TensorRT]]
arch = "x86_64"
cuda = "11.0"
git-tree-sha1 = "885578201b3d5e0ba3dd0c471ddefe7bbf4534f6"
lazy = true
libc = "glibc"
os = "linux"

    [[TensorRT.download]]
    sha256 = "627f142088823a21e8cada3ac0156ae3eaa5d038c9044d4f81f74f2687bd739c"
    url = "https://github.com/JuliaBinaryWrappers/TensorRT_jll.jl/releases/download/TensorRT-v10.4.0+0/TensorRT.v10.4.0.x86_64-linux-gnu-cuda+11.0.tar.gz"
[[TensorRT]]
arch = "x86_64"
cuda = "11.0"
git-tree-sha1 = "74d95bf1ae2852b03adcea3085eb10f1ff89f9eb"
lazy = true
os = "windows"

    [[TensorRT.download]]
    sha256 = "47b4eae4e52d12721f14694efc7edd7a71dfc1946f0538eadc41e9850a7ed7b7"
    url = "https://github.com/JuliaBinaryWrappers/TensorRT_jll.jl/releases/download/TensorRT-v10.4.0+0/TensorRT.v10.4.0.x86_64-w64-mingw32-cuda+11.0.tar.gz"
[[TensorRT]]
arch = "x86_64"
cuda = "12.0"
git-tree-sha1 = "fd6201d9daf2189ac645acc3a42186238f3e3e17"
lazy = true
libc = "glibc"
os = "linux"

    [[TensorRT.download]]
    sha256 = "15b5fd369e5c44448fe1db40542aef15758e09459bcf6032da7777bf25f3fb0a"
    url = "https://github.com/JuliaBinaryWrappers/TensorRT_jll.jl/releases/download/TensorRT-v10.4.0+0/TensorRT.v10.4.0.x86_64-linux-gnu-cuda+12.0.tar.gz"
[[TensorRT]]
arch = "x86_64"
cuda = "12.0"
git-tree-sha1 = "967637506a09ef484d3401407c92da994d0197c5"
lazy = true
os = "windows"

    [[TensorRT.download]]
    sha256 = "a23747546677d60396b68f05bd5c9c5a0888ad838da0847e6f8249c9c841bc81"
    url = "https://github.com/JuliaBinaryWrappers/TensorRT_jll.jl/releases/download/TensorRT-v10.4.0+0/TensorRT.v10.4.0.x86_64-w64-mingw32-cuda+12.0.tar.gz"
[[TensorRT]]
arch = "aarch64"
cuda = "12.0"
cuda_platform = "jetson"
git-tree-sha1 = "8b71cdb9bfd98bb4b1af4c33e1e12669061fbc6f"
lazy = true
libc = "glibc"
os = "linux"

    [[TensorRT.download]]
    sha256 = "129567783f289a3ca3e330a6296c6d693febca0aeddc797bf9b4291f4416f07b"
    url = "https://github.com/JuliaBinaryWrappers/TensorRT_jll.jl/releases/download/TensorRT-v10.4.0+0/TensorRT.v10.4.0.aarch64-linux-gnu-cuda_platform+jetson-cuda+12.0.tar.gz"
[[TensorRT]]
arch = "aarch64"
cuda = "12.0"
cuda_platform = "sbsa"
git-tree-sha1 = "6132b4a999e514902353be5845d15366716851bc"
lazy = true
libc = "glibc"
os = "linux"

    [[TensorRT.download]]
    sha256 = "71cbdc92bcacef69289f858047de90f8b5788b29c57bd46c88793a2f31c323fb"
    url = "https://github.com/JuliaBinaryWrappers/TensorRT_jll.jl/releases/download/TensorRT-v10.4.0+0/TensorRT.v10.4.0.aarch64-linux-gnu-cuda_platform+sbsa-cuda+12.0.tar.gz"
