[[TensorRT]]
arch = "x86_64"
cuda = "10.2"
git-tree-sha1 = "6103ff96d341f48da6fac448fab443e43b18c250"
lazy = true
libc = "glibc"
os = "linux"

    [[TensorRT.download]]
    sha256 = "6a8c3c38e1279dab8cf568a2e937f767eb305c39a29b7ef454ef158957acd489"
    url = "https://github.com/JuliaBinaryWrappers/TensorRT_jll.jl/releases/download/TensorRT-v8.0.1+0/TensorRT.v8.0.1.x86_64-linux-gnu-cuda+10.2.tar.gz"
[[TensorRT]]
arch = "x86_64"
cuda = "10.2"
git-tree-sha1 = "c95acb00ff9e8741399e8d46d72af5dfd640930d"
lazy = true
os = "windows"

    [[TensorRT.download]]
    sha256 = "e4760711cef224c86805e396faa030e688b7a1e8ae08b851b52c9fbe32623dca"
    url = "https://github.com/JuliaBinaryWrappers/TensorRT_jll.jl/releases/download/TensorRT-v8.0.1+0/TensorRT.v8.0.1.x86_64-w64-mingw32-cuda+10.2.tar.gz"
[[TensorRT]]
arch = "aarch64"
cuda = "10.2"
git-tree-sha1 = "d28350bab8104ef039ae6771ff0555e561c06bf2"
lazy = true
libc = "glibc"
os = "linux"

    [[TensorRT.download]]
    sha256 = "0c3a0d93c66a0238eafc0629f3729cc2356ee769a9165c98c820968ce7791b91"
    url = "https://github.com/JuliaBinaryWrappers/TensorRT_jll.jl/releases/download/TensorRT-v8.0.1+0/TensorRT.v8.0.1.aarch64-linux-gnu-cuda+10.2.tar.gz"
[[TensorRT]]
arch = "x86_64"
cuda = "11.0"
git-tree-sha1 = "7c7aedb4aa87a7881e86d4ec3cad21560bfea9d4"
lazy = true
libc = "glibc"
os = "linux"

    [[TensorRT.download]]
    sha256 = "b26657ffc1eb15b939150e4c81aef7d7f3f23215564a5d428b340fc4a5f75499"
    url = "https://github.com/JuliaBinaryWrappers/TensorRT_jll.jl/releases/download/TensorRT-v8.0.1+0/TensorRT.v8.0.1.x86_64-linux-gnu-cuda+11.0.tar.gz"
[[TensorRT]]
arch = "x86_64"
cuda = "11.0"
git-tree-sha1 = "c131e127d0874682a675ffe6ba186de93b41e080"
lazy = true
os = "windows"

    [[TensorRT.download]]
    sha256 = "bd843326f98f45c98961cd2ac0814d21e2b95aec86b5257340d2b0e5a3af27a5"
    url = "https://github.com/JuliaBinaryWrappers/TensorRT_jll.jl/releases/download/TensorRT-v8.0.1+0/TensorRT.v8.0.1.x86_64-w64-mingw32-cuda+11.0.tar.gz"
[[TensorRT]]
arch = "x86_64"
cuda = "11.1"
git-tree-sha1 = "db0b3bb7df72f8acba6bc68e0f07d6e9f4894174"
lazy = true
libc = "glibc"
os = "linux"

    [[TensorRT.download]]
    sha256 = "f1f397946542f25b63c428607e40fa110799bf6c205f50fed5143249c89f382b"
    url = "https://github.com/JuliaBinaryWrappers/TensorRT_jll.jl/releases/download/TensorRT-v8.0.1+0/TensorRT.v8.0.1.x86_64-linux-gnu-cuda+11.1.tar.gz"
[[TensorRT]]
arch = "x86_64"
cuda = "11.1"
git-tree-sha1 = "bff0d9fa6adbe81d0883eafc41443ee369901cd6"
lazy = true
os = "windows"

    [[TensorRT.download]]
    sha256 = "4669e9ba5ef12b524b1a8f74d913cb44555d950cb0c6764049219c3fb49eddcf"
    url = "https://github.com/JuliaBinaryWrappers/TensorRT_jll.jl/releases/download/TensorRT-v8.0.1+0/TensorRT.v8.0.1.x86_64-w64-mingw32-cuda+11.1.tar.gz"
[[TensorRT]]
arch = "x86_64"
cuda = "11.2"
git-tree-sha1 = "e3611438b2b4dc7d40e6f6316a294377bb65a6b3"
lazy = true
libc = "glibc"
os = "linux"

    [[TensorRT.download]]
    sha256 = "3f4a28c4ce6e4ef410faaca49215e28b9d300fdf22c4a232f34405c73b40b663"
    url = "https://github.com/JuliaBinaryWrappers/TensorRT_jll.jl/releases/download/TensorRT-v8.0.1+0/TensorRT.v8.0.1.x86_64-linux-gnu-cuda+11.2.tar.gz"
[[TensorRT]]
arch = "x86_64"
cuda = "11.2"
git-tree-sha1 = "cd03890f6c56aa039e3c3e487ecaaac310ea7ba2"
lazy = true
os = "windows"

    [[TensorRT.download]]
    sha256 = "42cfa40d8630f004635a3876e446f359d92f39c1b5b777e5ad552ccd45dfd1eb"
    url = "https://github.com/JuliaBinaryWrappers/TensorRT_jll.jl/releases/download/TensorRT-v8.0.1+0/TensorRT.v8.0.1.x86_64-w64-mingw32-cuda+11.2.tar.gz"
[[TensorRT]]
arch = "x86_64"
cuda = "11.3"
git-tree-sha1 = "609a96687dab79b062bb0c63657f8e5da60a82b9"
lazy = true
libc = "glibc"
os = "linux"

    [[TensorRT.download]]
    sha256 = "9d4843272bdc6d13483106872b566ee1060e2ca987fc2d8afb75ea626aaac832"
    url = "https://github.com/JuliaBinaryWrappers/TensorRT_jll.jl/releases/download/TensorRT-v8.0.1+0/TensorRT.v8.0.1.x86_64-linux-gnu-cuda+11.3.tar.gz"
[[TensorRT]]
arch = "powerpc64le"
cuda = "11.3"
git-tree-sha1 = "6f5f7db65c8f942f0a86fc024fd6caec9a43823e"
lazy = true
libc = "glibc"
os = "linux"

    [[TensorRT.download]]
    sha256 = "a87b07844f0f2db2478d1fd2d8185252c5a2dbb8ad0ee4402d9c7d3efc846b80"
    url = "https://github.com/JuliaBinaryWrappers/TensorRT_jll.jl/releases/download/TensorRT-v8.0.1+0/TensorRT.v8.0.1.powerpc64le-linux-gnu-cuda+11.3.tar.gz"
[[TensorRT]]
arch = "x86_64"
cuda = "11.3"
git-tree-sha1 = "87bf35dfaae26151bed480ad01d030b61cc8b21d"
lazy = true
os = "windows"

    [[TensorRT.download]]
    sha256 = "e1c174853ae93f41dd5efc576f523ed132a45fd09f067d5b0061223928d8a68b"
    url = "https://github.com/JuliaBinaryWrappers/TensorRT_jll.jl/releases/download/TensorRT-v8.0.1+0/TensorRT.v8.0.1.x86_64-w64-mingw32-cuda+11.3.tar.gz"
[[TensorRT]]
arch = "aarch64"
cuda = "11.3"
git-tree-sha1 = "5db5010b6221a4adf2f9f017e52bafb171e559b1"
lazy = true
libc = "glibc"
os = "linux"

    [[TensorRT.download]]
    sha256 = "797668548854d7b1bf9c668e66d7aafc7c2fb4e5fc24ab6a3553d5f34aad44a9"
    url = "https://github.com/JuliaBinaryWrappers/TensorRT_jll.jl/releases/download/TensorRT-v8.0.1+0/TensorRT.v8.0.1.aarch64-linux-gnu-cuda+11.3.tar.gz"
