[[TensorRT]]
arch = "x86_64"
cuda = "11.0"
git-tree-sha1 = "c4ba1d2a7f034393deb4ebbcdc75e62b600c6e18"
lazy = true
libc = "glibc"
os = "linux"

    [[TensorRT.download]]
    sha256 = "d77e7e809be6d1f5b046fb5a6cec20510105a1e629ce5d578dcc866d0a3b1425"
    url = "https://github.com/JuliaBinaryWrappers/TensorRT_jll.jl/releases/download/TensorRT-v10.7.0+0/TensorRT.v10.7.0.x86_64-linux-gnu-cuda+11.0.tar.gz"
[[TensorRT]]
arch = "x86_64"
cuda = "11.0"
git-tree-sha1 = "1cac1932c2dd869ac299e1b8ffbf268ad1225788"
lazy = true
os = "windows"

    [[TensorRT.download]]
    sha256 = "59292ccfb97265f5282722b7067f2ddcc93e31f548a2c291fc1a49cd5a24cc47"
    url = "https://github.com/JuliaBinaryWrappers/TensorRT_jll.jl/releases/download/TensorRT-v10.7.0+0/TensorRT.v10.7.0.x86_64-w64-mingw32-cuda+11.0.tar.gz"
[[TensorRT]]
arch = "x86_64"
cuda = "12.0"
git-tree-sha1 = "ff6c1e02e9fc1f30b79569902342a20b60205c9e"
lazy = true
libc = "glibc"
os = "linux"

    [[TensorRT.download]]
    sha256 = "825c883e12ac98ed1542a44f93087642d070fd7ce7b0ccfd1808ac0a74a316d4"
    url = "https://github.com/JuliaBinaryWrappers/TensorRT_jll.jl/releases/download/TensorRT-v10.7.0+0/TensorRT.v10.7.0.x86_64-linux-gnu-cuda+12.0.tar.gz"
[[TensorRT]]
arch = "x86_64"
cuda = "12.0"
git-tree-sha1 = "06c7055be80ee218b82de85fb0ad29f803957dfb"
lazy = true
os = "windows"

    [[TensorRT.download]]
    sha256 = "3012e2fc7f4793f189dbe501bbd7cc6f6d1c34ab7f038b6ee9f91e271ad6ebd6"
    url = "https://github.com/JuliaBinaryWrappers/TensorRT_jll.jl/releases/download/TensorRT-v10.7.0+0/TensorRT.v10.7.0.x86_64-w64-mingw32-cuda+12.0.tar.gz"
[[TensorRT]]
arch = "aarch64"
cuda = "12.0"
cuda_platform = "jetson"
git-tree-sha1 = "bc52e271f2749b480587981327ae82a6a65ece41"
lazy = true
libc = "glibc"
os = "linux"

    [[TensorRT.download]]
    sha256 = "66b3df0837757f9c1a368e35172b4a4b7a3dbef28e0777e3fcfbea78cdd99b18"
    url = "https://github.com/JuliaBinaryWrappers/TensorRT_jll.jl/releases/download/TensorRT-v10.7.0+0/TensorRT.v10.7.0.aarch64-linux-gnu-cuda_platform+jetson-cuda+12.0.tar.gz"
[[TensorRT]]
arch = "aarch64"
cuda = "12.0"
cuda_platform = "sbsa"
git-tree-sha1 = "a1a7d2dc6ad5702b5547645cce1791ddfecd80c9"
lazy = true
libc = "glibc"
os = "linux"

    [[TensorRT.download]]
    sha256 = "c98a9fbd27ad30e450ee493978a9a9a3521c1386801d77153d4e225f999cee38"
    url = "https://github.com/JuliaBinaryWrappers/TensorRT_jll.jl/releases/download/TensorRT-v10.7.0+0/TensorRT.v10.7.0.aarch64-linux-gnu-cuda_platform+sbsa-cuda+12.0.tar.gz"
