[[TensorRT]]
arch = "x86_64"
cuda = "10.2"
git-tree-sha1 = "44a5292acd855490be38b1a66fcb8ed86cbd5034"
lazy = true
libc = "glibc"
os = "linux"

    [[TensorRT.download]]
    sha256 = "c1e5d54cd10f74d18c3a35cc02b8dfa22277de1d4e8f20814334ba4f0cd470bd"
    url = "https://github.com/JuliaBinaryWrappers/TensorRT_jll.jl/releases/download/TensorRT-v8.0.3+0/TensorRT.v8.0.3.x86_64-linux-gnu-cuda+10.2.tar.gz"
[[TensorRT]]
arch = "x86_64"
cuda = "10.2"
git-tree-sha1 = "c3bc47f3f70713263897e09147821226883595a0"
lazy = true
os = "windows"

    [[TensorRT.download]]
    sha256 = "1c1fb209c44b0bf59898df485e24983ddbbce4068612abcec133a0c0c7426a17"
    url = "https://github.com/JuliaBinaryWrappers/TensorRT_jll.jl/releases/download/TensorRT-v8.0.3+0/TensorRT.v8.0.3.x86_64-w64-mingw32-cuda+10.2.tar.gz"
[[TensorRT]]
arch = "x86_64"
cuda = "11.0"
git-tree-sha1 = "4339c6a7e1014730bc965572a476d4e7a4779329"
lazy = true
libc = "glibc"
os = "linux"

    [[TensorRT.download]]
    sha256 = "adb991b1b48debfdd4012823383fdfd52d94490291eb13a90411cace880f7cdf"
    url = "https://github.com/JuliaBinaryWrappers/TensorRT_jll.jl/releases/download/TensorRT-v8.0.3+0/TensorRT.v8.0.3.x86_64-linux-gnu-cuda+11.0.tar.gz"
[[TensorRT]]
arch = "x86_64"
cuda = "11.0"
git-tree-sha1 = "50b7b769754a17003b98cb1e350ba16cd4a8d16e"
lazy = true
os = "windows"

    [[TensorRT.download]]
    sha256 = "8a035fcccb21d22b2c4b5fd98fc45b29c010919edece2816844d64337ecb3530"
    url = "https://github.com/JuliaBinaryWrappers/TensorRT_jll.jl/releases/download/TensorRT-v8.0.3+0/TensorRT.v8.0.3.x86_64-w64-mingw32-cuda+11.0.tar.gz"
[[TensorRT]]
arch = "x86_64"
cuda = "11.1"
git-tree-sha1 = "0ff91b3ab4c25e3feb22ab447e0a6c5870cf3a46"
lazy = true
libc = "glibc"
os = "linux"

    [[TensorRT.download]]
    sha256 = "94719fefd042f0ab9c9d3ac4aa478344ac827b2c12c935cbb2d7ea518cde3fc0"
    url = "https://github.com/JuliaBinaryWrappers/TensorRT_jll.jl/releases/download/TensorRT-v8.0.3+0/TensorRT.v8.0.3.x86_64-linux-gnu-cuda+11.1.tar.gz"
[[TensorRT]]
arch = "x86_64"
cuda = "11.1"
git-tree-sha1 = "e5ca1b8a6483492d2dfa8a79a6221b5a7d1e3e90"
lazy = true
os = "windows"

    [[TensorRT.download]]
    sha256 = "4edda31d7b0109b4cca73f66888be1d23a6b10b07cd1285aceb5a7681c82be18"
    url = "https://github.com/JuliaBinaryWrappers/TensorRT_jll.jl/releases/download/TensorRT-v8.0.3+0/TensorRT.v8.0.3.x86_64-w64-mingw32-cuda+11.1.tar.gz"
[[TensorRT]]
arch = "x86_64"
cuda = "11.2"
git-tree-sha1 = "96d32e28f3b8ee632e62cda6f5fb6048fea3a6f2"
lazy = true
libc = "glibc"
os = "linux"

    [[TensorRT.download]]
    sha256 = "e2f1b3ffa3db2d0e2e89f3986d30b9ab5acfc22366de09be29c626c2797ba7cb"
    url = "https://github.com/JuliaBinaryWrappers/TensorRT_jll.jl/releases/download/TensorRT-v8.0.3+0/TensorRT.v8.0.3.x86_64-linux-gnu-cuda+11.2.tar.gz"
[[TensorRT]]
arch = "x86_64"
cuda = "11.2"
git-tree-sha1 = "7586c2fc52105fe875178967c6890cff02165ca8"
lazy = true
os = "windows"

    [[TensorRT.download]]
    sha256 = "722d9042f3bdcdf78a44f13cc275dbb2fa4f6bce6c2b0a47d44e099fd9051a1e"
    url = "https://github.com/JuliaBinaryWrappers/TensorRT_jll.jl/releases/download/TensorRT-v8.0.3+0/TensorRT.v8.0.3.x86_64-w64-mingw32-cuda+11.2.tar.gz"
[[TensorRT]]
arch = "x86_64"
cuda = "11.3"
git-tree-sha1 = "9cf3abdd3dcf351a39300db3e87a13086fe123a7"
lazy = true
libc = "glibc"
os = "linux"

    [[TensorRT.download]]
    sha256 = "c174931713e5233f5c9c214c21491eb1eb314e1907fb529af5ce07cba921366f"
    url = "https://github.com/JuliaBinaryWrappers/TensorRT_jll.jl/releases/download/TensorRT-v8.0.3+0/TensorRT.v8.0.3.x86_64-linux-gnu-cuda+11.3.tar.gz"
[[TensorRT]]
arch = "x86_64"
cuda = "11.3"
git-tree-sha1 = "e9a506cfdd984e8aa69a8a52821ce9447ce3e1ee"
lazy = true
os = "windows"

    [[TensorRT.download]]
    sha256 = "d4782783e0196e59fd7b086ccca7e82273c9db47f4873faf89479e6a63df0249"
    url = "https://github.com/JuliaBinaryWrappers/TensorRT_jll.jl/releases/download/TensorRT-v8.0.3+0/TensorRT.v8.0.3.x86_64-w64-mingw32-cuda+11.3.tar.gz"
