# Autogenerated wrapper script for TensorRT_jll for powerpc64le-linux-gnu-cuda+11.3
export libnvinfer, libnvinfer_plugin, libnvonnxparser, libnvparsers, trtexec

using CUDNN_jll
JLLWrappers.@generate_wrapper_header("TensorRT")
JLLWrappers.@declare_library_product(libnvinfer, "libnvinfer.so.8")
JLLWrappers.@declare_library_product(libnvinfer_plugin, "libnvinfer_plugin.so.8")
JLLWrappers.@declare_library_product(libnvonnxparser, "libnvonnxparser.so.8")
JLLWrappers.@declare_library_product(libnvparsers, "libnvparsers.so.8")
JLLWrappers.@declare_executable_product(trtexec)
function __init__()
    JLLWrappers.@generate_init_header(CUDNN_jll)
    JLLWrappers.@init_library_product(
        libnvinfer,
        "lib/libnvinfer.so",
        nothing,
    )

    JLLWrappers.@init_library_product(
        libnvinfer_plugin,
        "lib/libnvinfer_plugin.so",
        nothing,
    )

    JLLWrappers.@init_library_product(
        libnvonnxparser,
        "lib/libnvonnxparser.so",
        nothing,
    )

    JLLWrappers.@init_library_product(
        libnvparsers,
        "lib/libnvparsers.so",
        nothing,
    )

    JLLWrappers.@init_executable_product(
        trtexec,
        "bin/trtexec",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
